### PR TITLE
re #126 Broken user flow (WIP)

### PR DESCRIPTION
**Pull request by kahboom**
**NOTE: This is still a work-in-progress, so please do not merge it in.**

Changes:
- Add filter text service and component.
- Bind to input on Connections list by adding shared service and component.
- Update Zone.js patch for better error handling.

In Progress:
- Fix: Properly load Create Connection view.
- Question/research: Using store service from multiple child components (parallel to one another) and making changes to a common object. Should the object (in this case, an Observable, which should be subscribed to and provide an array, more specifically the data or Connections list) instead be loaded from the parent component instead of each child component, along with its interface?
- Question/research: Related to the question above. Currently, there is nothing subscribing to a Restangular-loaded data set that can be used to filter through. This needs to be adjusted so that we can filter through this array with the provided filter and its corresponding service. Should this be done from a single place or each place it is needed? I understand that this data is cached by Angular so is not a question of performance, but for the sake of keeping things DRY.

### CODE REVIEW

**Comment by kahboom** [comment]
`ng test` is failing with the following error:

```
LOG: 'Created an instance of FilterTextService'
Chrome 55.0.2883 (Mac OS X 10.12.2) ConnectionsListToolbarComponent should create FAILED
	'ipaas-filter-text' is not a known element:
	1. If 'ipaas-filter-text' is an Angular component, then verify that it is part of this module.
	2. If 'ipaas-filter-text' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message. ("ntrol" placeholder="Filter By Name..." autocomplete="off" id="filterInput">
	          -->
	          [ERROR ->]<ipaas-filter-text (changed)="filterChanged($event)"></ipaas-filter-text>
	        </div>
	      </div>"): ConnectionsListToolbarComponent@20:10
	Error: Template parse errors:
	'ipaas-filter-text' is not a known element:
	1. If 'ipaas-filter-text' is an Angular component, then verify that it is part of this module.
	2. If 'ipaas-filter-text' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message. ("ntrol" placeholder="Filter By Name..." autocomplete="off" id="filterInput">
	          -->
	          [ERROR ->]<ipaas-filter-text (changed)="filterChanged($event)"></ipaas-filter-text>
	        </div>
	      </div>"): ConnectionsListToolbarComponent@20:10
	    at SyntaxError.ZoneAwareError (webpack:///~/zone.js/dist/zone.js:811:0 <- src/test.ts:127746:33)
	    at SyntaxError.BaseError [as constructor] (webpack:///~/@angular/compiler/src/facade/errors.js:26:0 <- src/test.ts:94774:16)
	    at new SyntaxError (webpack:///~/@angular/compiler/src/util.js:151:0 <- src/test.ts:7522:16)
	    at TemplateParser.parse (webpack:///~/@angular/compiler/src/template_parser/template_parser.js:140:0 <- src/test.ts:21883:19)
	    at JitCompiler._compileTemplate (webpack:///~/@angular/compiler/src/jit/compiler.js:360:25 <- src/test.ts:72017:68)
	    at webpack:///~/@angular/compiler/src/jit/compiler.js:243:47 <- src/test.ts:71900:62
	    at Set.forEach (native)
	    at JitCompiler._compileComponents (webpack:///~/@angular/compiler/src/jit/compiler.js:243:0 <- src/test.ts:71900:19)
	    at createResult (webpack:///~/@angular/compiler/src/jit/compiler.js:146:0 <- src/test.ts:71803:19)
	    at ZoneDelegate.invoke (webpack:///~/zone.js/dist/zone.js:242:0 <- src/test.ts:127177:26)
	    at AsyncTestZoneSpec.onInvoke (webpack:///~/zone.js/dist/async-test.js:49:0 <- src/test.ts:90038:39)
	    at ProxyZoneSpec.onInvoke (webpack:///~/zone.js/dist/proxy.js:76:0 <- src/test.ts:90730:39)
	    at ZoneDelegate.invoke (webpack:///~/zone.js/dist/zone.js:241:0 <- src/test.ts:127176:32)
	    at Zone.run (webpack:///~/zone.js/dist/zone.js:113:0 <- src/test.ts:127048:43)
	    at webpack:///~/zone.js/dist/zone.js:535:0 <- src/test.ts:127470:57
	Error: Uncaught (in promise): Error: Template parse errors:
	    at resolvePromise (webpack:///~/zone.js/dist/zone.js:501:0 <- src/test.ts:127436:31) [ProxyZone]
	    at resolvePromise (webpack:///~/zone.js/dist/zone.js:486:0 <- src/test.ts:127421:17) [ProxyZone]
	    at webpack:///~/zone.js/dist/zone.js:535:0 <- src/test.ts:127470:17 [ProxyZone]
	    at ProxyZoneSpec.onInvokeTask (webpack:///~/zone.js/dist/proxy.js:103:0 <- src/test.ts:90757:39) [ProxyZone]
	    at ZoneDelegate.invokeTask (webpack:///~/zone.js/dist/zone.js:274:0 <- src/test.ts:127209:40) [ProxyZone]
	    at Zone.runTask (webpack:///~/zone.js/dist/zone.js:151:0 <- src/test.ts:127086:47) [<root> => ProxyZone]
	    at drainMicroTaskQueue (webpack:///~/zone.js/dist/zone.js:433:0 <- src/test.ts:127368:35) [<root>]
	    at ZoneTask.invoke (webpack:///~/zone.js/dist/zone.js:349:0 <- src/test.ts:127284:25) [<root>]
	    at data.args.(anonymous function) (webpack:///~/zone.js/dist/zone.js:1376:0 <- src/test.ts:128311:25) [<root>]
	Error: Template parse errors:
	'ipaas-filter-text' is not a known element:
	1. If 'ipaas-filter-text' is an Angular component, then verify that it is part of this module.
	2. If 'ipaas-filter-text' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message. ("ntrol" placeholder="Filter By Name..." autocomplete="off" id="filterInput">
	          -->
	          [ERROR ->]<ipaas-filter-text (changed)="filterChanged($event)"></ipaas-filter-text>
	        </div>
	      </div>"): ConnectionsListToolbarComponent@20:10
	    at SyntaxError.ZoneAwareError (webpack:///~/zone.js/dist/zone.js:811:0 <- src/test.ts:127746:33)
	    at SyntaxError.BaseError [as constructor] (webpack:///~/@angular/compiler/src/facade/errors.js:26:0 <- src/test.ts:94774:16)
	    at new SyntaxError (webpack:///~/@angular/compiler/src/util.js:151:0 <- src/test.ts:7522:16)
	    at TemplateParser.parse (webpack:///~/@angular/compiler/src/template_parser/template_parser.js:140:0 <- src/test.ts:21883:19)
	    at JitCompiler._compileTemplate (webpack:///~/@angular/compiler/src/jit/compiler.js:360:25 <- src/test.ts:72017:68)
	    at webpack:///~/@angular/compiler/src/jit/compiler.js:243:47 <- src/test.ts:71900:62
	    at Set.forEach (native)
	    at JitCompiler._compileComponents (webpack:///~/@angular/compiler/src/jit/compiler.js:243:0 <- src/test.ts:71900:19)
	    at createResult (webpack:///~/@angular/compiler/src/jit/compiler.js:146:0 <- src/test.ts:71803:19)
	    at JitCompiler._compileModuleAndAllComponents (webpack:///~/@angular/compiler/src/jit/compiler.js:150:0 <- src/test.ts:71807:88)
	    at JitCompiler.compileModuleAndAllComponentsSync (webpack:///~/@angular/compiler/src/jit/compiler.js:97:0 <- src/test.ts:71754:21)
	    at TestingCompilerImpl.compileModuleAndAllComponentsSync (webpack:///~/@angular/compiler/bundles/compiler-testing.umd.js:482:0 <- src/test.ts:94444:35)
	    at TestBed._initIfNeeded (webpack:///~/@angular/core/bundles/core-testing.umd.js:761:0 <- src/test.ts:5193:40)
	    at TestBed.createComponent (webpack:///~/@angular/core/bundles/core-testing.umd.js:844:0 <- src/test.ts:5276:18)
	    at Function.TestBed.createComponent (webpack:///~/@angular/core/bundles/core-testing.umd.js:673:0 <- src/test.ts:5105:33)
	Expected undefined to be truthy.
	    at Object.<anonymous> (webpack:///src/app/connections/list-toolbar/list-toolbar.component.spec.ts:26:22 <- src/test.ts:109304:27) [ProxyZone]
	    at ProxyZoneSpec.onInvoke (webpack:///~/zone.js/dist/proxy.js:79:0 <- src/test.ts:90733:39) [ProxyZone]
	    at Zone.run (webpack:///~/zone.js/dist/zone.js:113:0 <- src/test.ts:127048:43) [ProxyZone => ProxyZone]
	    at Object.<anonymous> (webpack:///~/zone.js/dist/jasmine-patch.js:102:0 <- src/test.ts:90448:34) [ProxyZone]
Chrome 55.0.2883 (Mac OS X 10.12.2): Executed 37 of 37 (1 FAILED) (19.945 secs / 18.213 secs)
```

Proposed solutions don't appear to be working; I think this is likely related to lazy loading and will look into it.

**Comment by kahboom** [comment]
`ng test`:

screenshot 2017-01-25 12 41 12

`ng lint`:

screenshot 2017-01-25 12 41 23

**Comment by jimmidyson** [comment]
retest this please

**Comment by jimmidyson** [comment]
retest this please

**Comment by kahboom** [comment]
Closing this PR for a smaller, cleaned up version which is more focused for this sprint. The purpose of this PR was to fix the user flow for connections, which is not a priority for this sprint, however, still applies to integrations. I need to adjust the parent-child-sibling relationship and how they shared common modules. The first example of this is going to be the text filter, for which there is an issue [here](https://github.com/redhat-ipaas/ipaas-ui/issues/120). I'll open up a PR specific to that when ready.

**Pull request closed without merging**
