### PR TITLE
[WIP] Sprint 9

### PR DESCRIPTION
**Pull request by kahboom**
Ongoing work for Sprint 9 demo. :)

### CODE REVIEW

**Comment by kahboom** [comment]
Partial fix for sidebar styling, adding in modal confirmation for activation/deactivation next:

screenshot 2017-03-09 21 20 35

**Comment by kahboom** [comment]
screenshot 2017-03-09 21 42 31

**Comment by gashcrumb** [comment]
Yeah, that sidebar is lookin' much better!

**Comment by kahboom** [comment]
Support for multiple classes based on state:

screenshot 2017-03-09 22 05 05

**Comment by kahboom** [comment]
Minor aesthetic changes to selecting an action:

screenshot 2017-03-09 22 06 10

**Comment by kahboom** [comment]
Apply same UI changes to Action Configuration page:

screenshot 2017-03-09 22 13 09

**Comment by kahboom** [comment]
Bold has been removed! :D 

screenshot 2017-03-09 22 19 55

**Pull request merged**
