### PR TITLE
[WIP] Connection List Card Update

### PR DESCRIPTION
**Pull request by kahboom**
Now looks like this:

screenshot 2017-04-12 14 31 06

Next PR (coming soon) will include new icons (added to `assets` dir in this PR).

### CODE REVIEW

**Comment by kahboom** [comment]
@gashcrumb - Hold off on merging this PR; still discussing the layout and card height with @kcbabo .

**Comment by kahboom** [comment]
cc @kcbabo @jimmidyson @gashcrumb @chirino 

Latest changes:
- Update char limit for description to 100.
- Reverted back to the "slightly shorter" card that @sjcox-rh, @kcbabo , and I preferred (`height: 240px` vs PatternFly's traditional `height: 260px`).
- Add char limit to name of 20, with truncate trailing string.
- Add `title` text to `<h1>` with connection name.

## Regular View in Chrome

The best comparison is in the first row on the far right. See `lookie here, a connection` and `Please Work` (lol guess which one is mine and which one is @gashcrumb 's rofl).. :joy:

The description for `Please Work` is truncated more than it needs to be because when you zoom (see next screenshot), it will take up the full 3 lines of the description. Anything past that will overflow without the trailing string.

screenshot 2017-04-12 15 20 19


## Zoomed in Chrome
After doing `View > Zoom`. Note the full name of the Connection when you hover over it, regardless of whether or not it's truncated, @chirino .

screenshot 2017-04-12 15 20 36

cc @gashcrumb - This PR is pretty big; do you want me to add the image icons to this or in a separate PR? If separate, I need to wait for this to be merged as there will be conflicts otherwise. Ty!

**Comment by gashcrumb** [comment]
@kahboom there you go, merged :-)

**Comment by kahboom** [comment]
I can increase the truncate limit and just let it overflow without the trailing string if you'd like @kcbabo . Not a big deal, but whatever you prefer.

**Pull request merged**
