### PR TITLE
Update generated model

### PR DESCRIPTION
**Pull request by gashcrumb**
Don't merge yet, still working on this, currently updating current-flow.service.ts

### CODE REVIEW

**Comment by jimmidyson** [comment]
Model LGTM btw!

**Comment by kahboom** [comment]
+1 Let me know when it's okay to merge.

**Comment by gashcrumb** [comment]
This can be merged now, well unless the tests fail :-)

**Comment by gashcrumb** [comment]
oops, tests fail, lemme fix that

**Comment by gashcrumb** [comment]
@kahboom k, ready now

**Pull request merged**
