### PR TITLE
Reduce the vertical space each action/step take on the left side.

### PR DESCRIPTION
**Pull request by chirino**

### CODE REVIEW

**Comment by jimmidyson** [comment]
Is there any chance we can get before and after images attached to the pr for changes like this?

**Comment by chirino** [comment]
will do

**Comment by jimmidyson** [comment]
Thanks!

**Comment by chirino** [comment]
Before:
red_hat_ipaas_and_ipaas-ui_ ___sandbox_ipaas-ui_ _-bash_ _161x30
After:
red_hat_ipaas

**Pull request merged**
