### PR TITLE
Create connection wizard (page 1 and 3 mostly)

### PR DESCRIPTION
**Pull request by gashcrumb**
Given that there's a lot of work here am opening this PR now, don't merge it until I'm ready.

Currently looks like:

screencapture-localhost-4200-connections-create-connection-basics-1488386711734

### CODE REVIEW

**Comment by gashcrumb** [comment]
Yay, page 1 works, but am going to rework it a bit, first pass I made the view component also handle editing and creating, but I think it'd be better to separate out those concerns into different components.

screencapture-localhost-4200-connections-create-connection-basics-1488406904297

**Comment by gashcrumb** [comment]
Yay, it creates connections, have the form stuff in step 2 to implement now.  Just as proof here's two new connections I created:
screencapture-localhost-4200-connections-1488474856429

**Comment by jimmidyson** [comment]
@gashcrumb :beers: Let us know if you want to merge this piece by piece or if you want to wait until the whole thing is done?

**Comment by gashcrumb** [comment]
@jimmidyson I'd be fine with that actually, the next main bit here is getting the form built on page 2, I can do that in a separate PR.  Then this bit should be good to go, be good anyways to at least have a way of creating connections from the UI for testing the rest API.

**Comment by jimmidyson** [comment]
Fix up the linting and we can merge ;)

**Comment by jimmidyson** [comment]
> /home/ubuntu/ipaas-ui/src/app/connections/create-page/current-connection.ts[54, 23]: missing whitespace

**Comment by jimmidyson** [comment]
Thanks! [merge]

**Pull request merged**
