### PR TITLE
Fix #264 and IPAAS-272

### LINKED ISSUE #264: Create Integration: Delete Steps
## Overview
Add the ability to delete steps in the UI while creating integrations. Entails the following:
- Add HTML & SCSS to reflect designs (trash can on step) & incorporate logic.
- Add method(s) called by HTML for toast notifications once deleted, opening/closing confirmation modals, and actually deleting Connections in respective. component.
- Add logic to communicate with internal data store and SSE/Websocket for bi-directional model synchronization (and to initiate notifications)??
- Add modal to confirm action with user.
- Add toast notifications for action update.

### Relevant Designs
N/A

## Reference
- [JIRA: UI](https://issues.jboss.org/browse/IPAAS-272)
- [JIRA: User Story](https://issues.jboss.org/browse/IPAAS-247)

### PR DESCRIPTION
**Pull request by gashcrumb**

### CODE REVIEW

**Comment by kahboom** [comment]
@gashcrumb - Are we not waiting for checks to complete anymore before merging?

**Comment by gashcrumb** [comment]
@kahboom yeah, got impatient on this one, was running out the door :-)  so generally yes, think the Jenkins build hasn't been working though.

**Comment by kahboom** [comment]
@gashcrumb - Ah, still? And no worries, was honestly just wondering as I know you were running tests and linting locally.

**Comment by gashcrumb** [comment]
Yeah, was on a roll Friday, looks like this PR let a console.log slip through but I got it on a more recent PR.

**Pull request merged**
